name: Release

on:
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: write   # allow pushing commits

jobs:
  create-release:
    runs-on: ubuntu-latest

    steps:
      - name: Install zip
        run: sudo apt install -y zip

      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}

      - name: Get variables
        id: get_vars
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "DATE=$(date +'%D')" >> $GITHUB_ENV

      - name: Bump manifest version
        run: node .github/actions/bump-manifest-version.js
        env:
          TGT_RELEASE_VERSION: ${{ github.ref_name }}

      - name: Push version bump change
        uses: EndBug/add-and-commit@v9
        with:
          add: fxmanifest.lua
          push: true
          default_author: github_actions
          message: "chore: bump version to ${{ github.ref_name }}"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 20.19.0

      - name: Install dependencies
        run: npm ci
        working-directory: web

      - name: Run build
        run: npm run build
        working-directory: web
        env:
          CI: false

      - name: Bundle files
        run: |
          mkdir -p ./temp/orchid-bridge/web
          cp ./{README.md,LICENSE,fxmanifest.lua,init.lua} ./temp/orchid-bridge
          cp -r ./{data,modules,exports,framework} ./temp/orchid-bridge
          cp -r ./web/build ./temp/orchid-bridge/web/build
          cp ./web/LICENSE ./temp/orchid-bridge/web/build
          cd ./temp && zip -r ../orchid-bridge.zip ./orchid-bridge

      - name: Create release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: orchid-bridge.zip

      - name: Update tag
        uses: EndBug/latest-tag@v1
        with:
          ref: ${{ github.ref_name }}
