name: Create release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  create-release:
    if: github.actor_id != 210085057
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Grant write access to repository contents for creating releases
    steps:
      - name: Install zip
        run: sudo apt install zip

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}

      - name: Bump manifest version
        run: bun run .github/actions/bump-manifest-version.js
        env:
          TGT_RELEASE_VERSION: ${{ github.ref_name }}

      - name: Push version bump change
        uses: EndBug/add-and-commit@v9
        with:
          add: fxmanifest.lua
          push: true
          default_author: github_actions
          message: 'chore: bump version to ${{ github.ref_name }}'

      - name: Install dependencies
        run: bun install --frozen-lockfile
        working-directory: web

      - name: Run build script
        run: bun run build
        working-directory: web

      - name: Bundle files
        run: |
          mkdir -p ./temp/orchid-bridge/web
          cp ./{README.md,LICENSE,fxmanifest.lua,init.lua} ./temp/orchid-bridge
          cp -r ./{data,modules,exports,framework} ./temp/orchid-bridge
          cp -r ./web/build ./temp/orchid-bridge/web/build
          cp ./web/LICENSE ./temp/orchid-bridge/web/build
          cd ./temp && zip -r ../orchid-bridge.zip ./orchid-bridge

      - name: Create release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          prerelease: false
          files: orchid-bridge.zip  # Corrected to match the generated zip file

      - name: Update tag
        uses: EndBug/latest-tag@v1
        with:
          ref: ${{ github.ref_name }}